// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "../node_modules/reason-react/src/legacy/ReactDOMRe.bs.js";
import * as App$ReactTypescriptReasonTraining from "./components/App/App.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App$ReactTypescriptReasonTraining.make, {}), "root");

export {
  
}
/*  Not a pure module */
